#!/usr/bin/env bash

CONFIG_FILE=".env"
source $CONFIG_FILE

function request {
    if ! printenv | grep -q "WEB3_PRIVATE_KEY=."; then
        printf "Enter your wallet private key: "
        read -r private_key
        WEB3_PRIVATE_KEY=$private_key
    fi
    echo "Copy the JSON below to form your request:"
    printf '
  "messages": [{
    "role": "system",
    "content": "you are a helpful AI assistant"
  },
  {
    "role": "user",
    "content": "what is the animal order of the frog?"
  }],
  "options": {
    "temperature": 1.0
  }
'
    printf "\n(Paste JSON as one line) ➔ "
    read -r request
    request="{"model": $MODEL_NAME:$MODEL_VERSION, $request, "stream": false}"
}

if [ $# -gt 2 ]; then
    echo "Usage: scripts/run [--local] <request>"
    echo "Example: scripts/run 'What animal order do frogs belong to?'"
    exit 1
elif [ $# -eq 0 ]; then
    request
else
    for arg in $@; do
        if [ $# -eq 1 ] && ([ $1 == "--local" ] || [ $1 == "-l" ]); then
            if [ $# -ne 2 ]; then
                request
            fi
            echo "Running the Lilypad module Docker image locally..."
            lcoal=true
            REQUEST=$2
        else
            REQUEST=$1
        fi
    done
fi

# Base64 encode the request
BASE64_REQUEST=$(echo $full_request | base64 -w 0)
echo $WEB3_PRIVATE_KEY

if [ -z $lcoal ]; then
    commit_hash=$(git log --pretty=format:%H | head -n 1)
    MODULE=$GITHUB_REPO:$commit_hash
    echo "Running $MODULE on Lilypad Network..."
    echo "Original input: $request"
    echo "Base64 encoded: $BASE64_INPUT"
    lilypad run $MODULE -i request=$BASE64_REQUEST --web3-private-key=$WEB3_PRIVATE_KEY
else
    MODULE=$DOCKER_IMAGE:$VERSION
    echo "Running $MODULE locally..."
    echo "Original input: $request"
    echo "Base64 encoded: $BASE64_REQUEST"
    docker run $MODULE $BASE64_REQUEST
fi
